batch_size: 64
lr: 5e-5
gamma: 0.99
eps_start: 1.0
eps_end: 0.1
decay_steps: 10000
hidden_dim: 128 
n_episodes: 2000
max_steps_per_episode: 100
grid_size: 8
seed: 0
target_update_frequency: 500
evaluation_frequency: 100
replay_memory_size: 50000
warmup_start_size: 5000